/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/arquivos': RouteRecordInfo<'/arquivos', '/arquivos', Record<never, never>, Record<never, never>>,
    '/biblia': RouteRecordInfo<'/biblia', '/biblia', Record<never, never>, Record<never, never>>,
    '/doacoes': RouteRecordInfo<'/doacoes', '/doacoes', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/postagens': RouteRecordInfo<'/postagens', '/postagens', Record<never, never>, Record<never, never>>,
  }
}
